import './style.css'

const checks = ['Clear camera feed', 'Task completed', 'Hand in frame', 'Cameras in sync']
const ratings = ['Robot control', 'Movement smoothness', 'Task speed', 'Task completion', 'Camera composition']
let prismaPoints = 1240
let reputation = 500
const episodes=[
 {title:'Glass vial transfer',brief:'Inspect a delicate transfer sequence. One camera may be degraded.',clues:['Stable overhead view','Intermittent blur detected','Arm remains visible'],pass:[true,true,true,true],ratings:[4,4,3,5,4]},
 {title:'Emergency stop recovery',brief:'Review a factory recovery after an unexpected obstacle.',clues:['Robot stops before target','Task abandoned at 68%','Feeds remain synchronized'],pass:[true,false,true,true],ratings:[3,3,2,2,4]},
 {title:'Packing line sync test',brief:'Verify a high-speed packing run across all viewpoints.',clues:['Clear continuous footage','All boxes placed correctly','Right camera lags by 0.8s'],pass:[true,true,true,false],ratings:[5,5,5,5,4]},
 {title:'Cable routing trial',brief:'Find whether the robot keeps a safe, visible working path.',clues:['Left camera briefly loses arm','Route completed successfully','Clean sync signal'],pass:[true,true,false,true],ratings:[3,2,3,5,3]}
]
let currentEpisode

document.querySelector('#app').innerHTML = `
<main class="app-shell">
  <header class="topbar"><a class="brand">Prisma<sup>(X)</sup></a><nav><a class="active" id="station-nav">Validation Station</a><a id="progress-nav">Progress</a><a>Leaderboard</a></nav><div class="profile"><div><b id="vrs">500</b><small>VRS</small></div><div class="avatar">VA</div></div></header>
  <section class="status-row"><div><p class="eyebrow">EPISODE 0178 · TRAINING ARM GOLD</p><h1>Calibrate the future of physical AI.</h1></div><div class="points"><span>✦</span><div><small>PRISMA POINTS</small><strong id="points">1,240 PP</strong></div></div></section>
  <section class="mission-card"><div><span class="live-dot"></span> LIVE REVIEW SESSION</div><p id="episode-brief">Loading episode…</p><button id="new-episode">New episode ↻</button><span class="timer">02:48</span></section>
  <section class="station"><div class="feeds">${['LEFT CAMERA','HIGH CAMERA','RIGHT CAMERA'].map((name,i)=>`<article class="feed feed-${i+1}"><div class="feed-top"><span>${name}</span><span>● REC</span></div><div class="robot-scene"><div class="arm"><i></i><b></b><em></em></div><div class="crate"></div><div class="target"></div></div><div class="feed-bottom"><span>00:14:27</span><button>↗</button></div></article>`).join('')}</div><div class="playbar"><button id="play">▶</button><span>00:14</span><div class="timeline"><i></i></div><span>00:32</span><button class="speed">1×</button><button>◖</button></div></section>
  <section class="review-grid"><article class="review-card"><div class="card-heading"><div><p class="eyebrow">01 · REQUIRED CHECKS</p><h2>Validation criteria</h2></div><span class="step">4 / 4</span></div><div class="checks">${checks.map(item=>`<div class="check"><span>${item}</span><div class="choice"><button class="selected">Pass</button><button>Fail</button></div></div>`).join('')}</div></article><article class="review-card"><div class="card-heading"><div><p class="eyebrow">02 · QUALITY REVIEW</p><h2>Rate this episode</h2></div><span class="step">1 — 5</span></div><div class="ratings">${ratings.map(item=>`<div class="rating"><span>${item}</span><div class="dots">${[1,2,3,4,5].map(n=>`<button data-rating="${n}">${n}</button>`).join('')}</div></div>`).join('')}</div></article></section>
  <section class="submit-row"><p>Submit only when your review is complete. The Eval Engine will compare your judgment after submission.</p><button id="submit">Submit validation <span>→</span></button></section><section class="progress-panel"><p class="eyebrow">VALIDATOR PROFILE · SEASON 01</p><h1>Your signal is getting clearer.</h1><div class="progress-hero"><div><small>CURRENT RANK</small><h2>🌱 Seedling</h2><p><b id="progress-vrs">500</b> / 600 VRS to Observer</p><div class="meter"><i></i></div></div><div><small>ACTIVE STREAK</small><strong>03 <em>days</em></strong><p>Keep validating to earn a 7-day bonus.</p></div><div><small>NEXT REWARD</small><strong>2,000 <em>PP</em></strong><p>Unlocks at 7 consecutive days.</p></div></div><div class="progress-columns"><article><p class="eyebrow">ROBOT ARM TIERS</p><div class="tier unlocked"><span>🏅</span><div><b>Training Arm Gold</b><small>Default · Beginner</small></div><i>Active</i></div><div class="tier"><span>🖤</span><div><b>Training Arm Black</b><small>Unlock at VRS 600</small></div><i>Locked</i></div><div class="tier"><span>⚡</span><div><b>Arena Arm</b><small>Unlock at VRS 750</small></div><i>Locked</i></div></article><article><p class="eyebrow">STORY MODE</p><div class="chapter active-chapter"><span>01</span><div><b>Bootcamp</b><small>Learn the basics of validation</small></div><i>Start →</i></div><div class="chapter"><span>02</span><div><b>The Bad Data Crisis</b><small>Locked</small></div></div><div class="chapter"><span>03</span><div><b>Eval Engine Awakens</b><small>Locked</small></div></div></article></div></section><div class="toast" id="toast"></div><div class="result-backdrop" id="result"><section class="result-card"><p class="eyebrow">EVAL ENGINE REPORT · EPISODE 0178</p><h2>Validation complete</h2><div class="match"><span id="match">86%</span><small>ACCURACY MATCH</small></div><p id="result-copy">Strong calibration. Your evaluation closely matched the Eval Engine.</p><div class="reward-row"><div><small>PRISMA POINTS</small><b id="reward">+160 PP</b></div><div><small>REPUTATION</small><b>+12 VRS</b></div></div><button id="continue">Continue to station →</button></section></div>
  <footer class="social-footer"><span>FOLLOW THE SIGNAL</span><a href="https://x.com/mister_ntron" target="_blank" rel="noreferrer"><img src="/profiles/ntron.jpeg" alt="N-TRON"><b>N-TRON</b><small>@mister_ntron</small></a><a href="https://x.com/PrismaXai" target="_blank" rel="noreferrer"><img src="/profiles/prismax.jpeg" alt="PrismaX"><b>PrismaX</b><small>@PrismaXai</small></a></footer>
</main>`
function loadEpisode(){currentEpisode=episodes[Math.floor(Math.random()*episodes.length)];document.querySelector('#episode-brief').textContent=currentEpisode.title+' — '+currentEpisode.brief;document.querySelectorAll('.feed').forEach((feed,index)=>{feed.dataset.clue=currentEpisode.clues[index];feed.classList.toggle('alert',/blur|lags|loses/i.test(currentEpisode.clues[index]))});document.querySelectorAll('.choice').forEach(group=>group.querySelector('button').classList.add('selected'));document.querySelectorAll('.dots button').forEach(b=>b.classList.remove('chosen'))}
loadEpisode()
document.querySelector('#new-episode').onclick=loadEpisode
document.querySelectorAll('.choice button').forEach(button=>button.onclick=()=>{button.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected')})
document.querySelectorAll('.dots').forEach(group=>group.onclick=e=>{if(!e.target.matches('button'))return;group.querySelectorAll('button').forEach(b=>b.classList.toggle('chosen',+b.dataset.rating<=+e.target.dataset.rating))})
document.querySelectorAll('.robot-scene').forEach((scene,index)=>scene.innerHTML=`<video class="camera-video" src="/videos/video-${index+1}.mp4" muted loop playsinline preload="metadata"></video>`)
document.querySelectorAll('.camera-video').forEach(video=>video.play().catch(()=>{}))
document.querySelector('#play').onclick=e=>{const playing=e.target.textContent==='▶';document.querySelectorAll('.camera-video').forEach(video=>playing?video.play():video.pause());e.target.textContent=playing?'Ⅱ':'▶'}
document.querySelector('#submit').onclick=()=>{const choices=[...document.querySelectorAll('.choice')].map(g=>g.querySelector('.selected').textContent==='Pass');const score=[...document.querySelectorAll('.dots')].map((g,i)=>g.querySelectorAll('.chosen').length?g.querySelectorAll('.chosen').length:3);const wrong=choices.reduce((n,v,i)=>n+(v!==currentEpisode.pass[i]),0);const ratingError=score.reduce((n,v,i)=>n+Math.abs(v-currentEpisode.ratings[i]),0);const match=Math.max(30,100-wrong*14-ratingError*3);const reward=match>=90?700:match>=70?160:75;const vrsGain=match>=90?12:match>=70?6:2;document.querySelector('#match').textContent=`${match}%`;document.querySelector('#reward').textContent=`+${reward} PP`;document.querySelector('.reward-row div:last-child b').textContent=`+${vrsGain} VRS`;document.querySelector('#result-copy').textContent=match>=90?'Elite calibration. You earned an Eval Engine bonus.':match>=70?'Good calibration. Review the visual clues to improve further.':'The Eval Engine found important differences. Try another episode and watch the clues.';document.querySelector('#result').dataset.reward=reward;document.querySelector('#result').dataset.vrs=vrsGain;document.querySelector('#result').classList.add('show')}
document.querySelector('#continue').onclick=()=>{const result=document.querySelector('#result');prismaPoints+=Number(result.dataset.reward);reputation+=Number(result.dataset.vrs);document.querySelector('#points').textContent=`${prismaPoints.toLocaleString()} PP`;document.querySelector('#vrs').textContent=reputation;result.classList.remove('show')}
document.querySelector('#progress-nav').onclick=()=>{document.querySelector('#app').classList.add('progress-view');document.querySelector('#progress-vrs').textContent=reputation;document.querySelector('#progress-nav').classList.add('active');document.querySelector('#station-nav').classList.remove('active')}
document.querySelector('#station-nav').onclick=()=>{document.querySelector('#app').classList.remove('progress-view');document.querySelector('#station-nav').classList.add('active');document.querySelector('#progress-nav').classList.remove('active')}
document.querySelector('.active-chapter i').onclick=()=>{const briefing=document.createElement('div');briefing.className='briefing';briefing.innerHTML='<section><p class="eyebrow">CHAPTER 01 · BOOTCAMP</p><h2>Trust begins with attention.</h2><p>Factories are reporting corrupted robot sessions. Your first assignment is to identify a clean pick-and-place episode and calibrate your judgment against the Eval Engine.</p><div><small>MISSION REWARD</small><b>+100 PP · +5 VRS</b></div><button>Begin mission →</button></section>';document.body.append(briefing);briefing.querySelector('button').onclick=()=>{briefing.remove();document.querySelector('#station-nav').click()}}
